language: php

php:
  - 7.2
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

services:
  - docker

notifications:
  slack: 
    rooms:
      - esgi-iw:3xesgTA7LDncYCqnA2EShdA5#iw1-hdka
    on_success: always
    on_failure: always
    
  email:
    recipients:
      - driss.belaroussi.sio@gmail.com
      - kabaconde15@gmail.com

before_install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix ./src --dry-run
